import Layout from "@/components/layout"
import Head from "next/head"
import Link from "next/link"
import { useRouter } from "next/router"
import styles from "./error.module.css"

export default function Error() {
    const { errorCode } = useRouter().query
    return (
        <main className={styles.main}>
            <Head>
                <title>Error {errorCode}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout className={styles.shake}>
                <h1>:(</h1>
                <h2>Error <span className={styles.hightlight}>{errorCode}</span></h2>
                <Layout className={styles.linkContainer} type="montain" orientation="vertical">
                    <Link href="/">Go back to home</Link>
                </Layout>
            </Layout>
        </main>
    )
}