import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from './index.module.css'
import Layout from '@/components/layout'
import Link from 'next/link'
import { redirect } from 'next/dist/server/api-utils'
import { useState } from 'react'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [userName, setUserName] = useState('')
  const [loading, setLoading] = useState(false)
  const router = useRouter()

  const handleSearch = () => {
    if (userName.length > 0) {
      const url = '/user/' + userName
      router.replace(url)
      setLoading(true)
    }
  }

  const handleKeyEvent = (event) => {
    if (event.key === "Enter") {
      handleSearch()
    }
  }

  const getSearchComponent = () => {
    if (loading) {
      return <span className={styles.loading}>Loading</span>
    } else {
      return (
        <>
          <input placeholder='Enter a user name...' value={userName} onChange={e => setUserName(e.target.value)} onKeyDown={handleKeyEvent}></input>
          <button onClick={handleSearch}><ion-icon name="arrow-forward-outline"></ion-icon></button>
        </>
      )
    }
  }

  return (
    <main className={styles.main}>
      <Head>
        <title>Github profile viewer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout className={styles.w60} type="montain">
        { getSearchComponent() }
      </Layout>
    </main>
  )
}